(() => {
'use strict';
const C=window.EZYGO_CONFIG; const PHONE='919656309061';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const apiHeaders={apikey:C.SUPABASE_PUBLISHABLE_KEY,Authorization:`Bearer ${C.SUPABASE_PUBLISHABLE_KEY}`};
function esc(v=''){return String(v).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function arr(v){return Array.isArray(v)?v:[]}
function svgPlaceholder(label='Travel'){const txt=esc(label).slice(0,28);return `data:image/svg+xml;charset=UTF-8,${encodeURIComponent(`<svg xmlns="http://www.w3.org/2000/svg" width="900" height="1200"><defs><linearGradient id="g" x1="0" y1="0" x2="1" y2="1"><stop stop-color="#eef1f4"/><stop offset="1" stop-color="#dfe4e9"/></linearGradient></defs><rect width="100%" height="100%" fill="url(#g)"/><circle cx="450" cy="470" r="88" fill="#fff" opacity=".8"/><path d="M382 470h136M450 402v136" stroke="#b5bdc6" stroke-width="14" stroke-linecap="round"/><text x="450" y="650" text-anchor="middle" font-family="Arial" font-size="34" fill="#7f8994">${txt}</text></svg>`)}`}
function mediaUrl(path,label='Travel'){const raw=String(path||'').trim();if(!raw)return svgPlaceholder(label);if(raw.startsWith('data:')||raw.startsWith('blob:'))return raw;if(raw.startsWith('local:'))return raw.slice(6);if(raw.startsWith('/assets/'))return raw;if(/^https?:\/\//i.test(raw)){if(raw.startsWith(C.SUPABASE_URL))return raw;return svgPlaceholder(label)}const clean=raw.replace(/^site-media\//,'').replace(/^storage\/v1\/object\/public\/site-media\//,'').replace(/^\/+/, '');return `${C.SUPABASE_URL}/storage/v1/object/public/${C.STORAGE_BUCKET}/${clean}`}
async function rest(table,query=''){const r=await fetch(`${C.SUPABASE_URL}/rest/v1/${table}?${query}`,{headers:apiHeaders});if(!r.ok)throw new Error(`${table}: ${r.status}`);return r.json()}
function galleryHasImages(g={}){return arr(g.image_paths).some(x=>String(x||'').trim())}
function setGalleryAvailable(ok){const link=$('#galleryNav');const nav=document.querySelector('.nav');if(link)link.hidden=!ok;if(nav)nav.style.setProperty('--nav-columns',ok?'4':'3')}
async function gateGallery(){if(document.body.dataset.page==='gallery')return;try{const rows=await rest('galleries','select=id,image_paths&active=eq.true&order=sort_order.asc&limit=100');setGalleryAvailable(rows.some(galleryHasImages))}catch(e){console.warn('Gallery availability check failed',e);setGalleryAvailable(false)}}
function reveal(){document.body.classList.add('appReady');const s=$('#bootSplash');if(s)s.classList.add('done')}
async function submitFeedback(e){e.preventDefault();const name=$('#fbName')?.value.trim()||'',phone=$('#fbPhone')?.value.trim()||'',message=$('#fbMessage')?.value.trim()||'';if(!message)return;const btn=$('#feedbackForm .send'),old=btn.textContent;btn.disabled=true;btn.textContent='Sending…';try{const r=await fetch(`${C.SUPABASE_URL}/rest/v1/feedback`,{method:'POST',headers:{...apiHeaders,'Content-Type':'application/json',Prefer:'return=minimal'},body:JSON.stringify({name,phone,message})});if(!r.ok)throw new Error(await r.text());$('#feedbackForm').reset();let s=$('#feedbackStatus');if(!s){s=document.createElement('div');s.id='feedbackStatus';s.className='feedbackSuccess';$('#feedbackForm').appendChild(s)}s.textContent='Thank you. Your feedback has been sent.'}catch(err){console.error(err);alert('Could not send feedback right now. Please try again.')}finally{btn.disabled=false;btn.textContent=old}}
function initShell(){const y=$('#year');if(y)y.textContent=new Date().getFullYear();const c=$('#contactBtn');if(c)c.onclick=()=>window.open(`https://wa.me/${PHONE}?text=${encodeURIComponent('Hi EzyGo Travels, I would like to make a travel enquiry.')}`,'_blank');const f=$('#feedbackForm');if(f)f.onsubmit=submitFeedback;$$('.accBtn').forEach(btn=>btn.onclick=()=>btn.parentElement.classList.toggle('open'));gateGallery();if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('/service-worker.js').catch(()=>{}),{once:true});setTimeout(reveal,1400)}
document.addEventListener('contextmenu',e=>{if(e.target.closest('img'))e.preventDefault()});document.addEventListener('dragstart',e=>{if(e.target.closest('img'))e.preventDefault()});document.addEventListener('DOMContentLoaded',initShell);
window.EzyCommon={C,PHONE,$,$$,apiHeaders,esc,arr,mediaUrl,rest,galleryHasImages,setGalleryAvailable,reveal};
})();
