(() => {
'use strict';
const {$,$$,esc,arr,mediaUrl,rest,galleryHasImages,setGalleryAvailable,reveal}=window.EzyCommon;
let galleries=[],currentGallery=null,currentImageIndex=0,currentView='galleryPane';
function showLoading(){const grid=$('#galleryGrid');if(grid)grid.innerHTML=Array.from({length:window.innerWidth>=900?6:4},()=>`<div class="gallerySkeleton" aria-hidden="true"><div class="gallerySkeletonMedia skeletonGlow"></div><div class="skeletonLine short skeletonGlow"></div></div>`).join('')}
function render(){const list=galleries.filter(galleryHasImages);$('#galleryGrid').innerHTML=list.map(g=>{const cover=String(g.cover_path||'').trim()||arr(g.image_paths).find(x=>String(x||'').trim())||'';return `<button class="galleryCard" data-gallery="${esc(g.id)}"><img loading="lazy" decoding="async" src="${mediaUrl(cover,g.title)}" alt="${esc(g.title)}"><span>${esc(g.title)}</span></button>`}).join('')}
function openGallery(id,push=true){const g=galleries.filter(galleryHasImages).find(x=>String(x.id)===String(id));if(!g)return;currentGallery=g;$('#detailTitle').textContent=g.title||'';$('#detailDesc').textContent=g.description||'';const imgs=arr(g.image_paths).filter(x=>String(x||'').trim());$('#photoGrid').innerHTML=imgs.map((src,i)=>`<button class="photo" data-photo="${i}"><img loading="lazy" decoding="async" fetchpriority="auto" src="${mediaUrl(src,`${g.title} ${i+1}`)}" alt="${esc(g.title)} image ${i+1}"></button>`).join('');showOnly('galleryDetail');if(push)history.pushState({view:'galleryDetail',id:g.id},'','#gallery-'+g.id)}
function openLightbox(index=0){currentImageIndex=index;$('#lbTitle').textContent=currentGallery.title;const imgs=arr(currentGallery.image_paths).filter(x=>String(x||'').trim());$('#lbTrack').innerHTML=imgs.map((src,i)=>`<div class="lbSlide"><img loading="${i===index?'eager':'lazy'}" fetchpriority="${i===index?'high':'auto'}" decoding="async" src="${mediaUrl(src,`${currentGallery.title} ${i+1}`)}" alt="${esc(currentGallery.title)}"></div>`).join('');$('#lightbox').classList.add('open');document.body.style.overflow='hidden';requestAnimationFrame(()=>{$('#lbTrack').scrollLeft=$('#lbTrack').clientWidth*index;updateCount(index)})}
function updateCount(i){currentImageIndex=i;$('#lbCount').textContent=`${i+1} / ${arr(currentGallery?.image_paths).filter(x=>String(x||'').trim()).length}`}
function closeLightbox(){$('#lightbox').classList.remove('open');document.body.style.overflow=''}
function showOnly(view,scrollTop=true){currentView=view;$('#galleryPane').style.display=view==='galleryPane'?'block':'none';$('#galleryDetail').style.display=view==='galleryDetail'?'block':'none';if(scrollTop)window.scrollTo({top:0,behavior:'auto'});requestAnimationFrame(updateBack)}
function updateBack(){const b=$('#backBtn');const show=currentView!=='galleryPane'||window.scrollY>80;b.classList.toggle('is-hidden',!show)}
function handleBack(){if(window.scrollY>80){window.scrollTo({top:0,behavior:'smooth'});return}if(currentView!=='galleryPane'){history.back();return}updateBack()}
async function load(){showLoading();try{galleries=await rest('galleries','select=*&active=eq.true&order=sort_order.asc');const visible=galleries.filter(galleryHasImages);if(!visible.length){setGalleryAvailable(false);location.replace('service.html');return}setGalleryAvailable(true);render()}catch(err){console.error(err);$('#galleryGrid').innerHTML='<div class="empty">Gallery could not be loaded right now.</div>'}finally{reveal()}}
document.addEventListener('DOMContentLoaded',()=>{load();$('#galleryGrid').onclick=e=>{const c=e.target.closest('[data-gallery]');if(c)openGallery(c.dataset.gallery)};$('#photoGrid').onclick=e=>{const b=e.target.closest('[data-photo]');if(b&&currentGallery)openLightbox(Number(b.dataset.photo))};$('#backBtn').onclick=handleBack;window.addEventListener('scroll',updateBack,{passive:true});$('#lbClose').onclick=closeLightbox;$('#lbPrev').onclick=()=>{if(!currentGallery)return;const n=Math.max(0,currentImageIndex-1);$('#lbTrack').scrollTo({left:$('#lbTrack').clientWidth*n,behavior:'smooth'});updateCount(n)};$('#lbNext').onclick=()=>{if(!currentGallery)return;const n=Math.min(arr(currentGallery.image_paths).filter(x=>String(x||'').trim()).length-1,currentImageIndex+1);$('#lbTrack').scrollTo({left:$('#lbTrack').clientWidth*n,behavior:'smooth'});updateCount(n)};window.addEventListener('popstate',e=>{const st=e.state;if(st?.view==='galleryDetail')openGallery(st.id,false);else showOnly('galleryPane',true)});history.replaceState({view:'galleryPane'},'',location.pathname);updateBack()})
})();
