(() => {
'use strict';
const {PHONE,$,$$,esc,arr,mediaUrl,rest,reveal}=window.EzyCommon;
let cards=[],groups=[],currentCard=null,currentVisaImageIndex=0,currentVisaImages=[],activeType='',activeDays='',isLoadingCards=true,currentView='explorePane';
let mediaObserver=null; const preloadedMedia=new Set();
function cleanGroupName(v=''){return String(v).replace(/^[\s🌏🌍]+/u,'').trim()}
function loadingCards(count=8){return Array.from({length:count},()=>`<article class="skeletonCard" aria-hidden="true"><div class="skeletonPoster skeletonGlow"></div><div class="skeletonLine skeletonGlow"></div><div class="skeletonLine short skeletonGlow"></div></article>`).join('')}
function showCardLoading(){const grid=$('#cardGrid');if(grid)grid.innerHTML=loadingCards(window.innerWidth>=900?10:6)}
function preloadMedia(paths,priority='low'){for(const path of paths||[]){const url=mediaUrl(path);if(!url||url.startsWith('data:')||preloadedMedia.has(url))continue;preloadedMedia.add(url);const img=new Image();img.decoding='async';try{img.fetchPriority=priority}catch(_){}img.src=url}}
function observeMediaAhead(){if(mediaObserver)mediaObserver.disconnect();if(!('IntersectionObserver'in window))return;mediaObserver=new IntersectionObserver(entries=>{for(const entry of entries){if(!entry.isIntersecting)continue;const el=entry.target;if(el.dataset.id){const card=cards.find(x=>String(x.id)===String(el.dataset.id));if(card)preloadMedia([card.cover_path,...arr(card.detail_paths).slice(0,2)],'low')}mediaObserver.unobserve(el)}},{rootMargin:'1800px 0px',threshold:.01});$$('[data-id]').forEach(el=>mediaObserver.observe(el))}
function cardMarkup(c,index=999){const valid=c.validity||(Number(c.days)?`${c.days} Days`:'Check details');return `<article class="card" data-id="${esc(c.id)}"><div class="poster"><img loading="${index<20?'eager':'lazy'}" fetchpriority="${index<8?'high':'auto'}" decoding="async" src="${mediaUrl(c.cover_path,c.country)}" alt="${esc(c.country)}"><div class="identity"><div class="flagcircle">${esc(c.flag||'✈️')}</div><div class="country">${esc(c.country)}</div></div><div class="hoverpeek"><span>${esc(c.type||'Visa')}</span><b>${esc(valid)}${c.fee?' · '+esc(c.fee):''}</b><small>View full details</small></div><div class="cardmeta"><div class="metagrid"><div><span class="label">Type</span><span class="value">${esc(c.type||'Visa')}</span></div><div><span class="label">Valid</span><span class="value">${esc(valid)}</span></div></div></div></div><div class="below"><div class="line1">${esc(c.date_label||'Visa assistance')}</div><div class="line2">${esc(c.deadline||'Contact us for current processing details')}</div>${c.fee?`<div class="fee">${esc(c.fee)}</div>`:''}</div></article>`}
function renderCards(){const q=($('#search')?.value||'').trim().toLowerCase();let list=cards.filter(c=>!q||[c.country,c.type,c.group_name,c.description].join(' ').toLowerCase().includes(q));if(activeType)list=list.filter(c=>c.type===activeType);if(activeDays){const n=Number(activeDays);list=list.filter(c=>n===0?Number(c.days||0)===0:Number(c.days||0)<=n)}const groupOrder=groups.length?groups:[...new Set(cards.map(c=>c.group_name))].map((name,i)=>({name,sort_order:i}));let html='',visibleIndex=0;for(const g of groupOrder){const items=list.filter(c=>c.group_name===g.name);if(!items.length)continue;html+=`<div class="visaGroup">${esc(cleanGroupName(g.name))}</div>${items.map(c=>cardMarkup(c,visibleIndex++)).join('')}`}if(!html){if(isLoadingCards||!cards.length){showCardLoading();return}html='<div class="empty">No matching visa options.</div>'}$('#cardGrid').innerHTML=html;requestAnimationFrame(observeMediaAhead)}
function buildTypeChips(){const types=[...new Set(cards.map(c=>c.type).filter(Boolean))];$('#typeChips').innerHTML=types.map(t=>`<button class="chip" data-type="${esc(t)}">${esc(t)}</button>`).join('');$$('[data-type]').forEach(b=>b.onclick=()=>{activeType=activeType===b.dataset.type?'':b.dataset.type;$$('[data-type]').forEach(x=>x.classList.toggle('active',x.dataset.type===activeType))})}
function setVisaSlide(index,animate=true){const track=$('#packageTrack');if(!track)return;const total=currentVisaImages.length||1;currentVisaImageIndex=Math.max(0,Math.min(total-1,index));track.style.transition=animate?'transform .30s cubic-bezier(.22,.61,.36,1)':'none';track.style.transform=`translate3d(${-currentVisaImageIndex*100}%,0,0)`;$$('#packageDots [data-visa-dot]').forEach((dot,i)=>{dot.classList.toggle('active',i===currentVisaImageIndex);dot.setAttribute('aria-current',i===currentVisaImageIndex?'true':'false')})}
function bindVisaSlider(){const track=$('#packageTrack'),dots=$('#packageDots');if(!track||track.dataset.sliderBound==='1')return;track.dataset.sliderBound='1';let startX=0,startY=0,active=false;track.addEventListener('pointerdown',e=>{if(e.pointerType==='mouse'&&e.button!==0)return;active=true;startX=e.clientX;startY=e.clientY;try{track.setPointerCapture(e.pointerId)}catch(_){}});track.addEventListener('pointerup',e=>{if(!active)return;active=false;const dx=e.clientX-startX,dy=e.clientY-startY;if(Math.abs(dx)>38&&Math.abs(dx)>Math.abs(dy))setVisaSlide(currentVisaImageIndex+(dx<0?1:-1));else setVisaSlide(currentVisaImageIndex)});track.addEventListener('pointercancel',()=>{active=false;setVisaSlide(currentVisaImageIndex)});track.addEventListener('dragstart',e=>e.preventDefault());dots.addEventListener('click',e=>{const dot=e.target.closest('[data-visa-dot]');if(dot)setVisaSlide(Number(dot.dataset.visaDot))})}
function openCardDetail(id,push=true){const c=cards.find(x=>String(x.id)===String(id));if(!c)return;currentCard=c;currentVisaImages=[c.cover_path,...arr(c.detail_paths)].filter(Boolean);preloadMedia(currentVisaImages,'high');const sliderItems=currentVisaImages.length?currentVisaImages:[''];$('#packageTrack').innerHTML=sliderItems.map((src,i)=>`<div class="detailSlide"><img loading="${i===0?'eager':'lazy'}" fetchpriority="${i===0?'high':'auto'}" decoding="async" src="${mediaUrl(src,`${c.country} ${i+1}`)}" alt="${esc(c.country)} image ${i+1}" draggable="false"></div>`).join('');$('#packageDots').innerHTML=sliderItems.length>1?sliderItems.map((_,i)=>`<button type="button" class="detailDot ${i===0?'active':''}" data-visa-dot="${i}" aria-label="Show image ${i+1}" aria-current="${i===0?'true':'false'}"></button>`).join(''):'';$('#packageFlag').textContent=c.flag||'✈️';$('#packageType').textContent=c.type||'Visa';$('#packageTitle').textContent=c.country||'';$('#packageDesc').textContent=c.description||'';$('#packageDays').textContent='Contact now';$('#packageDate').textContent='Check now';$('#packagePhone').textContent='+91 96563 09061';$('#packageDocs').innerHTML=arr(c.documents).map(d=>`<div class="docItem"><span class="docTick">✓</span><span>${esc(d)}</span></div>`).join('');showOnly('cardDetail');bindVisaSlider();setVisaSlide(0,false);if(push)history.pushState({view:'cardDetail',id:c.id},'','#visa-'+c.id)}
function showOnly(view,scrollTop=true){currentView=view;$('#explorePane').style.display=view==='explorePane'?'block':'none';$('#cardDetail').style.display=view==='cardDetail'?'block':'none';$('#tools').style.display=view==='explorePane'?'grid':'none';if(scrollTop)window.scrollTo({top:0,behavior:'auto'});requestAnimationFrame(updateBackButton)}
function updateBackButton(){const btn=$('#backBtn');if(!btn)return;const shouldShow=currentView!=='explorePane'||window.scrollY>80;btn.classList.toggle('is-hidden',!shouldShow)}
function handleBack(){if(window.scrollY>80){window.scrollTo({top:0,behavior:'smooth'});return}if(currentView!=='explorePane'){history.back();return}updateBackButton()}
async function load(){showCardLoading();try{[groups,cards]=await Promise.all([rest('visa_groups','select=*&active=eq.true&order=sort_order.asc'),rest('visa_cards','select=*&active=eq.true&order=sort_order.asc')]);isLoadingCards=false;renderCards();buildTypeChips()}catch(err){console.error(err);isLoadingCards=true;showCardLoading()}finally{reveal()}}
document.addEventListener('DOMContentLoaded',()=>{load();$('#search').addEventListener('input',renderCards);$('#cardGrid').onclick=e=>{const c=e.target.closest('[data-id]');if(c)openCardDetail(c.dataset.id)};$('#backBtn').onclick=handleBack;window.addEventListener('scroll',updateBackButton,{passive:true});$('#filterBtn').onclick=()=>$('#filterModal').classList.add('open');$('#closeFilter').onclick=()=>$('#filterModal').classList.remove('open');$('#applyFilter').onclick=()=>{$('#filterModal').classList.remove('open');renderCards()};$('#clearFilter').onclick=()=>{activeType='';activeDays='';$$('.chip').forEach(x=>x.classList.remove('active'));renderCards()};$$('[data-days]').forEach(b=>b.onclick=()=>{activeDays=activeDays===b.dataset.days?'':b.dataset.days;$$('[data-days]').forEach(x=>x.classList.toggle('active',x.dataset.days===activeDays))});$('#packageEnquire').onclick=()=>currentCard&&window.open(`https://wa.me/${PHONE}?text=${encodeURIComponent(`Hi EzyGo Travels, I would like details about ${currentCard.country}.`)}`,'_blank');$('#packageValidityFact').onclick=()=>currentCard&&window.open(`https://wa.me/${PHONE}?text=${encodeURIComponent(`Hi EzyGo Travels, please confirm visa validity for ${currentCard.country}.`)}`,'_blank');$('#packageAvailabilityFact').onclick=()=>currentCard&&window.open(`https://wa.me/${PHONE}?text=${encodeURIComponent(`Hi EzyGo Travels, please check current availability/details for ${currentCard.country}.`)}`,'_blank');window.addEventListener('popstate',e=>{const st=e.state;if(st?.view==='cardDetail')openCardDetail(st.id,false);else showOnly('explorePane',true)});history.replaceState({view:'explorePane'},'',location.pathname);updateBackButton()})
})();
